version: "3.7"

services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: mssql
        restart: unless-stopped
        networks:  
            - modular_monolith  
        environment:
            - ACCEPT_EULA=Y
        env_file:
            - db.env
        ports: 
            - 1433:1433
        volumes:
            - mssql:/var/opt/mssql
    postgres:
        image: postgres:12-alpine
        container_name: postgres
        restart: unless-stopped
        networks:
            - modular_monolith
        env_file:
            - db.env
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data

networks:
    modular_monolith:
        name: modular-monolith-network

volumes:
    mssql:
        driver: local
    postgres:
        driver: local